config/routes.rb
Survey::Application.routes.draw do
  resources :survey_forms
  get "survey/open"
  get "survey/:id" , to: 'survey#show', as: 'survey'
  get "survey_forms/:id/report" , to: 'survey_forms#report', as: 'report_survey_form'
  patch "survey_delivery" , to: 'survey#delivery', as: 'survey_deliver'

  devise_for :users, :path_prefix => 'my'
  resources :users
  
  get "home/index"
  

  root 'home#index'

  

end

app/models/survey_form.rb
class SurveyForm < ActiveRecord::Base
	belongs_to :user
	has_many :survey_fields, :dependent => :destroy
	has_many :answers

	attr_accessor :type_list

	validates :title, presence: true
	validates :description, presence: true

	accepts_nested_attributes_for :survey_fields, reject_if: proc { |attributes| attributes['title'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :answers

	# accepts_nested_attributes_for :answers, reject_if: :valid_answers? 

	# def valid_answers?(attributes)

 #      if attributes['value_answer'].blank?
 #      	Rails.logger.debug "!!!!!!!! ERROR"
 #      	errors[:base] << "can't be greater than total value"
 #      	errors.add(:answers, "cannot contain the characters !@#%*()_-+=")
 #      	self.errors.add :base, 'Please ensure that Interest field do not contain HTML(< and >) tags'
 #      end

 #      !attributes['value_answer'].blank?
	# end

end

app/models/survey_type.rb
class SurveyType

	attr_reader :id, :name, :label

	def initialize args=nil
		if args != nil
			args.each do |k,v|
				instance_variable_set("@#{k}", v) unless v.nil?
			end
		end
	end

	@@TYPES = [
		SurveyType.new(:id => 1, :name => "text_type", :label => "Texto"),
		SurveyType.new(:id => 2, :name => "combo_box", :label => "Combo Box"),
		SurveyType.new(:id => 3, :name => "radio", :label => "Radio")
	]

	def self.types
		@@TYPES
	end

end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController

  before_action :set_survey_form, only: [:delivery]
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Pesquisa interativa", :survey_forms_path 

  # GET /survey_forms
  # GET /survey_forms.json
  def open
    @survey_forms = SurveyForm.where(restrict: false)
  end

  def show
    @survey_form = SurveyForm.find(params[:id])
    @identifier = Time.new.try(:strftime,'%Y%m%d%H%M%S%L') + @survey_form.id.to_s
  end

  def delivery
    respond_to do |format|
      if @survey_form.update(survey_form_params)
        SurveyForm.increment_counter :responses , @survey_form.id
        format.html { flash[:notice] = 'Pesquisa respondida com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def survey_form_params
      params.require(:survey_form).permit(:id, answers_attributes: [
          :label_answer, :value_answer, :survey_field_id, :identifier, :user_id
        ])
    end

    def set_survey_form
      @survey_form = SurveyForm.find(survey_form_params[:id])
    end
end 

app/views/survey/_open.html.erb
<div class="well well-lg center" >
 <table class="table">
    <thead>
      <tr>
        <th>Titulo</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @survey_forms.each do |survey_form| %>
        <tr>
          <td><%= link_to survey_form.title, survey_path(survey_form.id), :style => "background-color: transparent; color: black" %></td>
          <td style="text-align: center"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/survey/delivery.html.erb
<div class="container"> 
	<% if flash[:notice] %>
		<div id="notice" class="alert alert-info"><%= notice %></div>
	<% end %>
	<div class="well well-lg center" >
		<h3>Obrigado por responder nossa pesquisa</h3>
	</div>
	<%= link_to "<button class='btn btn-danger' type='button'>Voltar</button>".html_safe, root_path %>
	<%= render "layouts/footer" %>
</div>

app/views/survey/open.html.erb
<div class="container"> 
  <% if flash[:notice] %>
    <div id="notice" class="alert alert-info"><%= notice %></div>
  <% end %>
  <div class="page-header">
    <h1>Veja como funciona</h1>
    <p class="lead">Se uma pessoa/empresa quer saber a opinião sobre um determinado assunto, basta apenas se cadastrar em nosso site para gerar essa pesquisa e sair distribuindo o link para todos que quiserem.</p>
  </div>
  <% if !user_signed_in? %>
    <p class="lead">Para ter acesso as pesquisas restritas disponíveis para você, crie um cadastro agora mesmo!</p>  
    <p>
      <%= button_to 'Cadastre-se', new_user_registration_path, :class => "btn btn-primary btn-lg", :method => "get" %> 
    <% end %>
  </p>
  <%- if  @survey_forms.size > 0 %>
    <p class="small">Abaixo temos algumas pesquisa abertas que podem ser respondidas anonimamente. Apenas o solicitante recebera os dados garantindo assim seu anonimato.</p>
    <%= render "open", survey_forms: @survey_forms %>
  <% end %>
  <%= render "layouts/footer" %>
</div>

app/views/survey/show.html.erb
<div class="container"> 
  	<%= render "survey_forms/components/survey", survey_form: @survey_form, preview: false %>
</div>