config/routes.rb
Survey::Application.routes.draw do
  resources :survey_forms
  get "survey/open"
  get "survey/:id" , to: 'survey#show', as: 'survey'
  get "survey_forms/:id/report" , to: 'survey_forms#report', as: 'report_survey_form'
  patch "survey_delivery" , to: 'survey#delivery', as: 'survey_deliver'

  devise_for :users, :path_prefix => 'my'
  resources :users
  
  get "home/index"
  

  root 'home#index'

  

end

app/controllers/survey_forms_controller.rb
class SurveyFormsController < ApplicationController
  before_action :set_survey_form, only: [:show, :edit, :update, :destroy, :report]

  before_filter :authenticate_user!

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Pesquisa interativa", :survey_forms_path 

  # GET /survey_forms
  # GET /survey_forms.json
  def index
    if current_user.isAdmin
      @survey_forms = SurveyForm.all
    else 
      @survey_forms = SurveyForm.where(:user => current_user)
    end
  end

  # GET /survey_forms
  # GET /survey_forms.json
  def open
    @survey_forms = SurveyForm.where(restrict: false)
  end

  # GET /survey_forms/1
  # GET /survey_forms/1.json
  def show
  end

  # GET /survey_forms/new
  def new
    @survey_form = SurveyForm.new
  end

  # GET /survey_forms/1/edit
  def edit
  end

  def report
    @answer_group = {}
    chart = {}
    chart1 = {}
    @pie_chart = {}

    qtdRepostas = 0

    @survey_form.survey_fields.each do |survey_field|
      respostas = Answer.where(:survey_form => @survey_form, :survey_field => survey_field)
      qtdRepostas = respostas.size

      respostas.each do |resposta|
        if @answer_group[resposta.identifier] == nil
          @answer_group[resposta.identifier] = Array.new
        end
        @answer_group[resposta.identifier].push resposta

        if chart[survey_field.title] == nil
          chart[survey_field.title] = Array.new
        end
        chart[survey_field.title].push resposta.label_answer
      end
    end

    chart.map do | key, value |
      if chart1[key] == nil
         chart1[key] = {}
      end

      chart[key].each do | item |
        if chart1[key][item] == nil
          chart1[key][item] = 1
        else 
          chart1[key][item] = chart1[key][item] + 1
        end
        
      end 
    end
    chart1.map do | key, value |

      @pie_chart[key] = Array.new
      chart1[key].map do | key1, value1 |
        local = (chart1[key][key1] * 100) / qtdRepostas
        @pie_chart[key].push JSON.parse('{"label": "'+key1[0,18]+'...",  "data":'+(local).to_s+'}')
      end

    end

  end

  # POST /survey_forms
  # POST /survey_forms.json
  def create
    @survey_form = SurveyForm.new(survey_form_params)
    @survey_form.responses = 0
    @survey_form.user = current_user

    respond_to do |format|
      if @survey_form.save
        format.html { redirect_to @survey_form, notice: 'Pesquisa interativa criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @survey_form }
      else
        format.html { render action: 'new' }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_forms/1
  # PATCH/PUT /survey_forms/1.json
  def update
    respond_to do |format|
      if @survey_form.update(survey_form_params)
        format.html { redirect_to @survey_form, notice: 'Pesquisa interativa atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_forms/1
  # DELETE /survey_forms/1.json
  def destroy
    @survey_form.destroy
    respond_to do |format|
      format.html { redirect_to survey_forms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_form
      @survey_form = SurveyForm.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_form_params
      params.require(:survey_form).permit(:title, :requestor, :description, :restrict,
        survey_fields_attributes: 
          [:title, :survey_type_id, :id, :_destroy, :mandatory, survey_field_options_attributes: 
            [:label, :value, :id]]
          )
    end
end

app/helpers/survey_forms_helper.rb
module SurveyFormsHelper
	
end

app/views/survey_forms/_edit_survey_templates.html.erb
<%= render "survey_forms/components/text" %>
<%= render "survey_forms/components/combobox" %>
<%= render "survey_forms/components/radio" %>

<script type="text/javascript">

  var TEXT = 1;
  var COMBOBOX = 2;
  var RADIO = 3;

  var data = { "survey_fields": <%=h f.object.survey_fields.to_json(:include =>[:survey_field_options]).to_s.html_safe %>};

  $.each( data.survey_fields, function( key, survey_field ) {

    var interConterCB = 1;
    var interConterRadio = 1;
    $.each( survey_field.survey_field_options, function( key, survey_field_option ) {
     
      survey_field_option.father=conter;

      if(survey_field.survey_type_id == COMBOBOX){
        conterComboBox["values_field_"+conter] = {index:interConterCB,father:conter}
        survey_field_option.index=interConterCB;
        interConterCB ++;
      }
      else if(survey_field.survey_type_id == RADIO){
        conterRadio["values_field_"+conter] = {index: interConterRadio,father:conter}
        survey_field_option.index = conter + "_" + interConterRadio;
        survey_field_option.index_counter = interConterRadio;
        interConterRadio ++;
      }
    });

    survey_field.index=conter;
    
    if(survey_field.survey_type_id == TEXT){
      var template = $('#textTpl').html();
      var html = Mustache.to_html(template, survey_field);
      $("#campos").append(html);

    } else if(survey_field.survey_type_id == COMBOBOX){
      var template = $('#comboboxTpl').html();
      var html = Mustache.to_html(template, survey_field);
      $("#campos").append(html);

    } else if(survey_field.survey_type_id == RADIO){
      var template = $('#radioTpl').html();
      var html = Mustache.to_html(template, survey_field);
      $("#campos").append(html);
    }
    
    conter ++;
  });
  $("#campos").show();  
  $("#survey_form_type_list").val("");
</script>

app/views/survey_forms/_form.html.erb
<%= form_for(@survey_form, :html => {:class => 'form-horizontal', :onsubmit => "return submit_form()"}) do |f| %>
  <% if @survey_form.errors.any? %>
    <div class="alert alert-danger">
      <h2>Problemas na solicitação!</h2>
       <% @survey_form.errors.full_messages.each do |msg| %>
        <ul><%= msg %></ul>
      <% end %>
    </div>
  <% end %>

  <dl class="dl-horizontal">
    <dt><%= f.label :user%></dt>
    <dd><%= current_user.email %></dd>
  </dl>

  <div class="form-group">
    <%= f.label :restrict, :class => "col-lg-2 control-label"%>  
    <div class="col-lg-10">
      <%= f.select :restrict, [['Não', false], ['Sim', true]] , {}, {:class => "form-control"}%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= f.text_field :title, :autofocus => true, :class => "form-control", :placeholder => t("app.placeholder.survey_form.title")%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => "form-control", :placeholder => t("app.placeholder.survey_form.description")%>
    </div>
  </div>

  <div id="campos" class="form-group" style="display: none"></div>
 
  <div class="form-group">
    <%= f.label :add_type_list, :class => "col-lg-2 control-label"%>
    <div class="col-lg-10">
     <%= f.select :type_list, options_for_select(SurveyType.types.collect{|p| [ p.label, p.id ] }), {prompt: t("app.select_a_type_of_field")}, 
      {:class =>  "form-control", :onChange => 'addFieldType(this.value)' } %>
    </div>
  </div>
  <script type="text/javascript">
    var conter = 0;
    var conterComboBox = [];
    var conterRadio = [];
  </script>

  <%- if f.object.survey_fields.size > 0 %>
    <%= render "edit_survey_templates", f: f %>
  <% else %>
    <%= render "new_survey_templates" %>
  <% end %>

  <script type="text/javascript">

    function submit_form(){
      
    }
    
    function addFieldType(value){
      data = {index:conter};
      //TextField
      if(value == "1"){
        var template = $('#textTpl').html();
        var html = Mustache.to_html(template, data);
        $("#campos").append(html);
        $("#campos").show();

        // console.log($("#field"+conter).html())
        // $("#field"+conter).draggable();

        $("#survey_form_type_list").val("");
        conter ++;
        
      } 
      //ComboBox
      else if(value == "2"){
        var template = $('#comboboxTpl').html();
        var html = Mustache.to_html(template, data);
        $("#campos").append(html);
        $("#campos").show();

        $("#survey_form_type_list").val("");
        conter ++;
      }

      //Radio
      else if(value == "3"){
        var template = $('#radioTpl').html();
        var html = Mustache.to_html(template, data);
        $("#campos").append(html);
        $("#campos").show();

        $("#survey_form_type_list").val("");
        conter ++;
      }
    }
    function removeFieldType(id){
      $("#"+id+ "_remove").val(1);
      $("#"+id).hide();
    }

    function setMandatory(obj){

      index = obj.id.split("_")[2];
      enunciado = $("#enunciado_" + index + "_pv").html();

      $("#"+obj.id + "_val").val(obj.value)
      if(obj.value == 'true'){
        $("#enunciado_" + index + "_pv").append("*");
      } else {
        $("#enunciado_" + index + "_pv").html(enunciado.substring(0,enunciado.length -1));
      }
    }

    function changeEnunciado(obj){
      add_mandatory = false;
      if(enunciado.indexOf("*") > -1 && enunciado.indexOf("*") == (enunciado.length -1)){
        add_mandatory = true;
      }
      $("#" + obj.id + "_pv").html(obj.value);
      if(add_mandatory){
        $("#enunciado_" + index + "_pv").append("*");
      }
    }
  </script>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <div class="row">
        <div class="col-md-6"><%= link_to "<button class='btn btn-danger' type='button'>Voltar</button>".html_safe, survey_forms_path %></div>
        <div class="col-md-6" style="text-align: right"><%= f.submit :class=>"btn btn-success", :value=>"Salvar"%></div>
      </div>
    </div>
  </div>
<% end %>

app/views/survey_forms/_new_survey_templates.html.erb
<%= render "survey_forms/components/combobox" %>
<%= render "survey_forms/components/text" %>
<%= render "survey_forms/components/radio" %>

app/views/survey_forms/edit.html.erb
<div class="container"> 
	<%= render_breadcrumbs :builder => ::BootstrapBreadcrumbsBuilder, :separator => "&raquo;" %>
	<div class="well well-lg center" >
		<h3><span class="label label-default">Edição</span> Pesquisa interativa</h3>
		<%= render 'form' %>
	</div>
</div>

app/views/survey_forms/index.html.erb
<div class="container"> 
  <%= render_breadcrumbs :builder => ::BootstrapBreadcrumbsBuilder, :separator => "&raquo;" %>
  <div class="well well-lg center" >
    <h3><span class="label label-default">Lista</span> Pesquisa interativa</h3>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th>Titulo</th>
          <th>Solicitante</th>
          <th>Respostas</th>
          <th>Restrita</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @survey_forms.each do |survey_form| %>
          <tr>
            <td><%= link_to survey_form.title, survey_form, :style => "background-color: transparent; color: black" %></td>
            <td><%= survey_form.user.email %></td>
            <td><%= survey_form.responses %></td>
            <td> <%= survey_form.restrict == true ? "Sim" : "Não" %></td>  
            <td style="text-align: center"><%= link_to content_tag(:span, "", :class => "glyphicon glyphicon-edit"), edit_survey_form_path(survey_form), :style=>"background-color: transparent; color: black" %></td>
            <td style="text-align: center"><%= link_to content_tag(:span, "", :class => "glyphicon glyphicon-remove"), survey_form, method: :delete, data: { confirm: 'Tem certeza?' }, :style=>"background-color: transparent; color: black"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


     <%= button_to 'Nova', new_survey_form_path, :class => "btn btn-large btn-primary", :method => "get" %> 
  </div>

</div>

app/views/survey_forms/new.html.erb
<div class="container"> 
	<%= render_breadcrumbs :builder => ::BootstrapBreadcrumbsBuilder, :separator => "&raquo;" %>
	<div class="well well-lg center" >
		<h3><span class="label label-default">Nova</span> Pesquisa interativa</h3>
		<%= render 'form' %>
	</div>
</div>

app/views/survey_forms/open.html.erb
<div class="container"> 
  <div class="well well-lg center" >
    <h3><span class="label label-default">Lista</span> Pesquisa interativa</h3>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th>Titulo</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
       
      </tbody>
    </table>
  </div>
</div>

app/views/survey_forms/report.html.erb
<style type="text/css">

	.demo-container {
		position: relative;
		height: 150px;
	}
</style>

<div class="container"> 
	<div class="well well-lg center" >
		<% if flash[:notice] %>
			<div id="notice" class="alert alert-info"><%= notice %></div>
		<% end %>
		<h3><span class="label label-default">Report</span> Pesquisa interativa</h3>
		<br>	
		<p>
		  <strong>Titulo:</strong>
		  <%= @survey_form.title %>
		</p>
		<p>
		  <strong>Respostas:</strong>
		  <%= @survey_form.responses %>
		</p>
		
		<%= render "/survey_forms/chart/pie"%>

		<p>
			<%- @answer_group.map { |key, value| %>
				
				<div class="panel panel-default" id="<%= key %>">
				  <div class="panel-heading" style="height: 40px">
				  	<div class="col-md-8">Usuário: 
				  		<% if @answer_group[key][0].user != nil %>
				  			<%= link_to @answer_group[key][0].user.name, user_path(@answer_group[key][0].user, :returnTo => request.original_url), :style => "background-color: transparent; color: black" %>
				  		<% else %>
				  			Anonimo
				  		<% end %>
				  		</div>
					<div class="col-md-4">Identificador: <i><%= key %></i></div>
				  </div>
				  <div class="panel-body">
				<%- @answer_group[key].each { |answer| %>
					<b><%= answer.survey_field.title %></b><br>
					Resposta: <%= answer.label_answer %> <br>
				<% } %>
				
			 		</div>
				</div>
			<% } %>
		</p>

		<br>
		<p>
			<%= link_to "<button class='btn btn-danger' type='button'>Voltar</button>".html_safe, survey_form_path(@survey_form) %>
    	</p>
	</div>
</div>

app/views/survey_forms/show.html.erb
<div class="container"> 
	<%= render_breadcrumbs :builder => ::BootstrapBreadcrumbsBuilder, :separator => "&raquo;" %>
	<div class="well well-lg center" >
		<% if flash[:notice] %>
			<div id="notice" class="alert alert-info"><%= notice %></div>
		<% end %>
		<h3><span class="label label-default">Visualização</span> Pesquisa interativa</h3>
		<br>	
		<p>
		  <strong>Titulo:</strong>
		  <%= @survey_form.title %>
		</p>
		<p>
		  <strong>Solicitante:</strong>
		  <%= @survey_form.user.email %>
		</p>

		<p>
		  <strong>Respostas:</strong>
		  <%= @survey_form.responses %>
		  <%- if @survey_form.responses > 0 %>
		  	<%= link_to "<button class='btn btn-success' type='button'>Ver relatório</button>".html_safe, report_survey_form_path(@survey_form) %>
		  <% end %>
		</p>
		<p>
		  <strong>Restrita:</strong>
		  <%= @survey_form.restrict == true ? "Sim" : "Não" %>
		</p>

		<div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Pré visualisação</h3>
          </div>
          <div class="panel-body">
          	<%= render "survey_forms/components/survey", survey_form: @survey_form, preview: true %>
          </div>
        </div>

		<br>
		<p>
			<%= link_to "<button class='btn btn-danger' type='button'>Voltar</button>".html_safe, survey_forms_path %>
	        <%= link_to "<button class='btn btn btn-info' type='button'>Editar</button>".html_safe, edit_survey_form_path(@survey_form) %>
    	</p>
	</div>
</div>