config/routes.rb
Survey::Application.routes.draw do
  resources :survey_forms
  get "survey/open"
  get "survey/:id" , to: 'survey#show', as: 'survey'
  get "survey_forms/:id/report" , to: 'survey_forms#report', as: 'report_survey_form'
  patch "survey_delivery" , to: 'survey#delivery', as: 'survey_deliver'

  devise_for :users, :path_prefix => 'my'
  resources :users
  
  get "home/index"
  

  root 'home#index'

  

end

app/controllers/survey_forms_controller.rb
class SurveyFormsController < ApplicationController
  before_action :set_survey_form, only: [:show, :edit, :update, :destroy, :report]

  before_filter :authenticate_user!

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Pesquisa interativa", :survey_forms_path 

  # GET /survey_forms
  # GET /survey_forms.json
  def index
    if current_user.isAdmin
      @survey_forms = SurveyForm.all
    else 
      @survey_forms = SurveyForm.where(:user => current_user)
    end
  end

  # GET /survey_forms
  # GET /survey_forms.json
  def open
    @survey_forms = SurveyForm.where(restrict: false)
  end

  # GET /survey_forms/1
  # GET /survey_forms/1.json
  def show
  end

  # GET /survey_forms/new
  def new
    @survey_form = SurveyForm.new
  end

  # GET /survey_forms/1/edit
  def edit
  end

  def report
    @answer_group = {}
    chart = {}
    chart1 = {}
    @pie_chart = {}

    qtdRepostas = 0

    @survey_form.survey_fields.each do |survey_field|
      respostas = Answer.where(:survey_form => @survey_form, :survey_field => survey_field)
      qtdRepostas = respostas.size

      respostas.each do |resposta|
        if @answer_group[resposta.identifier] == nil
          @answer_group[resposta.identifier] = Array.new
        end
        @answer_group[resposta.identifier].push resposta

        if chart[survey_field.title] == nil
          chart[survey_field.title] = Array.new
        end
        chart[survey_field.title].push resposta.label_answer
      end
    end

    chart.map do | key, value |
      if chart1[key] == nil
         chart1[key] = {}
      end

      chart[key].each do | item |
        if chart1[key][item] == nil
          chart1[key][item] = 1
        else 
          chart1[key][item] = chart1[key][item] + 1
        end
        
      end 
    end
    chart1.map do | key, value |

      @pie_chart[key] = Array.new
      chart1[key].map do | key1, value1 |
        local = (chart1[key][key1] * 100) / qtdRepostas
        @pie_chart[key].push JSON.parse('{"label": "'+key1[0,18]+'...",  "data":'+(local).to_s+'}')
      end

    end

  end

  # POST /survey_forms
  # POST /survey_forms.json
  def create
    @survey_form = SurveyForm.new(survey_form_params)
    @survey_form.responses = 0
    @survey_form.user = current_user

    respond_to do |format|
      if @survey_form.save
        format.html { redirect_to @survey_form, notice: 'Pesquisa interativa criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @survey_form }
      else
        format.html { render action: 'new' }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_forms/1
  # PATCH/PUT /survey_forms/1.json
  def update
    respond_to do |format|
      if @survey_form.update(survey_form_params)
        format.html { redirect_to @survey_form, notice: 'Pesquisa interativa atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_forms/1
  # DELETE /survey_forms/1.json
  def destroy
    @survey_form.destroy
    respond_to do |format|
      format.html { redirect_to survey_forms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_form
      @survey_form = SurveyForm.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_form_params
      params.require(:survey_form).permit(:title, :requestor, :description, :restrict,
        survey_fields_attributes: 
          [:title, :survey_type_id, :id, :_destroy, :mandatory, survey_field_options_attributes: 
            [:label, :value, :id]]
          )
    end
end

app/helpers/survey_forms_helper.rb
module SurveyFormsHelper
	
end

app/views/survey_forms/components/_combobox.html.erb
<script id="comboboxTpl" type="text/template">
  <div id="field{{index}}" class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-2"><h3 class="panel-title"><%= t("app.survey_field.label_name", :field_name =>t("app.survey_field.combobox.name")) %></h3> <span onclick="removeFieldType('field{{index}}')" style="cursor: pointer"><%=t "app.remove" %></span></div>
        <div class="col-md-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%=t "app.preview" %></h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-lg-2 control-label" id="enunciado_{{index}}_pv" for="survey_form_Enunciado">{{title}}</label>
                <div class="col-lg-10">
                  <select class="form-control" id="cb_{{index}}_pv" >
                    <option value=""><%= t "app.survey_field.combobox.options" %></option>
                     {{#survey_field_options}}
                       <option value="{{value}}">{{label}}</option>
                     {{/survey_field_options}}
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-lg-2 control-label"><%=t "app.enunciado" %></label>
        <div class="col-lg-10">
          <input type="text" id="enunciado_{{index}}" name="survey_form[survey_fields_attributes][][title]" class="form-control" placeholder="<%=t "app.enunciado" %>" onFocusOut="changeEnunciado(this)" value="{{title}}"/>
          <input type="hidden" name="survey_form[survey_fields_attributes][][survey_type_id]" value="2" />
          <input type="hidden" name="survey_form[survey_fields_attributes][][order]" value="{{index}}" />
          {{#id}}
            <input type="hidden" name="survey_form[survey_fields_attributes][][id]" value="{{id}}" />
            <input type="hidden" id="field{{index}}_remove" name="survey_form[survey_fields_attributes][][_destroy]" value="0" />
          {{/id}}
        </div>
      </div>
      <div id="values_field_{{index}}_div">
         {{#survey_field_options}}
          <div class="form-group">
            <label class="col-lg-2 control-label" for="survey_form_Enunciado"><%=t "app.value" %> {{index}}</label>
            <div class="col-lg-10">
              <input type="text" id="valor_{{index}}_{{father}}" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][label]" class="form-control" placeholder="Alternativa {{index}}" onFocusOut="setValueComboBox(this)" value="{{label}}" />
              <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][value]" value="{{index}}" />
              {{#id}}
                <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][id]" value="{{id}}" />
                <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][_destroy]" value="0" />
              {{/id}}
            </div>
          </div>
         {{/survey_field_options}}
      </div>
      <div class="row">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-10"> <span onclick="addValueComboBox('values_field_{{index}}',{{index}})"  style="cursor: pointer"><%=t "app.survey_field.combobox.add_value" %> </span></div>
      </div>
    </div>
  </div>
</script>

<script id="combobox_fields_Tpl" type="text/template">
  <div class="form-group">
    <label class="col-lg-2 control-label">Valor {{index}}</label>
    <div class="col-lg-10">
      <input type="text" id="valor_{{index}}_{{father}}" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][label]" class="form-control" placeholder="<%= t "app.survey_field.combobox.placeholder.option" %> {{index}}" onFocusOut="setValueComboBox(this)" />
      <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][value]" value="{{index}}" />
    </div>
  </div>
</script>

<script type="text/javascript">
  function addValueComboBox(field,idFather){
    valor = conterComboBox[field];
    if(valor == undefined){
      conterComboBox[field] = {index:1,father:idFather}
    } else {
      valor.index ++;
      conterComboBox[field] = valor;
    }
    data = conterComboBox[field];
    var template = $('#combobox_fields_Tpl').html();
    var html = Mustache.to_html(template, data);
    $("#" + field +  "_div").append(html);
  }

  function setValueComboBox(obj){
    idItem = obj.id.split("_")[1];
    idFather = obj.id.split("_")[2];  
    if(obj.value == ""){
      $("#cb_"+ idFather + "_pv option[value='"+idItem+"']").remove();
    } else {
      if($("#cb_"+ idFather + "_pv option[value='"+idItem+"']").length == 0){
        $("#cb_"+ idFather + "_pv").append( new Option(obj.value,idItem));
      } else {
        $("#cb_"+ idFather + "_pv option[value='"+idItem+"']").text(obj.value);
      } 
    }
    
  }
</script>

app/views/survey_forms/components/_radio.html.erb
<script id="radioTpl" type="text/template">
  <div id="field{{index}}" class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-2"><h3 class="panel-title"><%= t("app.survey_field.label_name", :field_name =>t("app.survey_field.radio.name")) %></h3> <span onclick="removeFieldType('field{{index}}')" style="cursor: pointer"><%=t "app.remove" %></span></div>
        <div class="col-md-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%=t "app.preview" %></h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-lg-2 control-label" id="enunciado_{{index}}_pv" for="survey_form_Enunciado">{{title}}</label>
                <div class="col-lg-10" id="radio_{{index}}_pv">
                	 {{#survey_field_options}}
                       <div class="radio" id="radio_{{index}}_pv">
            						  <label>
            						    <input type="radio" name="" value="{{value}}"><label id="radio_{{index}}_pv_label">{{label}}</label>
            						  </label>
						          </div>
                     {{/survey_field_options}}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-lg-2 control-label"><%=t "app.enunciado" %></label>
        <div class="col-lg-10">
          <input type="text" id="enunciado_{{index}}" name="survey_form[survey_fields_attributes][][title]" class="form-control" placeholder="<%=t "app.enunciado" %>" onFocusOut="changeEnunciado(this)" value="{{title}}"/>
          <input type="hidden" name="survey_form[survey_fields_attributes][][survey_type_id]" value="3	" />
          <input type="hidden" name="survey_form[survey_fields_attributes][][order]" value="{{index}}" />
          {{#id}}
            <input type="hidden" name="survey_form[survey_fields_attributes][][id]" value="{{id}}" />
            <input type="hidden" id="field{{index}}_remove" name="survey_form[survey_fields_attributes][][_destroy]" value="0" />
          {{/id}}
        </div>
      </div>
      <div id="values_field_{{index}}_div">
         {{#survey_field_options}}
          <div class="form-group">
            <label class="col-lg-2 control-label" for="survey_form_Enunciado"><%=t "app.value" %> {{index_counter}}</label>
            <div class="col-lg-10">
              <input type="text" id="valor_{{index}}_{{father}}" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][label]" class="form-control" placeholder="Alternativa {{index}}" onFocusOut="setValueRadio(this)" value="{{label}}" />
              <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][value]" value="{{index}}" />
              {{#id}}
                <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][id]" value="{{id}}" />
                <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][_destroy]" value="0" />
              {{/id}}
            </div>
          </div>
         {{/survey_field_options}}
      </div>
      <div class="row">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-10"> <span onclick="addValueRadio('values_field_{{index}}',{{index}})"  style="cursor: pointer"><%=t "app.survey_field.radio.add_value" %> </span></div>
      </div>
    </div>
  </div>
</script>

<script id="radio_fields_Tpl" type="text/template">
  <div class="form-group" id="opt_{{father}}_{{index}}">
    <label class="col-lg-2 control-label">Valor {{index}}</label>
    <div class="col-lg-10">
      <input type="text" id="valor_{{father}}_{{index}}" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][label]" class="form-control" placeholder="<%= t "app.survey_field.radio.placeholder.option" %> {{index}}" onFocusOut="setValueRadio(this)" />
      <input type="hidden" name="survey_form[survey_fields_attributes][][survey_field_options_attributes][][value]" value="{{index}}" />
    </div>
  </div>
</script>

<script id="radio_fields_option_Tpl" type="text/template">
	<div class="radio" id="radio_{{index}}_pv">
	  <label>
	    <input type="radio" name="" value="{{value}}"><label id="radio_{{index}}_pv_label">{{label}}</label>
	  </label>
	</div>
</script>


<script type="text/javascript">
  function addValueRadio(field,idFather){

    valor = conterRadio[field];
    if(valor == undefined){
      conterRadio[field] = {index:1,father:idFather}
    } else {
      valor.index ++;
      conterRadio[field] = valor;
    }
    data = conterRadio[field];
    var template = $('#radio_fields_Tpl').html();
    var html = Mustache.to_html(template, data);
    $("#" + field +  "_div").append(html);
  }

  function setValueRadio(obj){
    idItem = obj.id.split("_")[2];
    idFather = obj.id.split("_")[1];  

    data = {
    	index:idFather + "_"  + idItem,
    	label: obj.value
	}
	if(obj.value == ""){
		 $("#radio_"+data.index+"_pv").remove()
		 $("#opt_"+data.index).remove()
		 conterRadio["values_field_" + idFather].index --;
	} else {
		if($("#radio_" + data.index +  "_pv").html() != undefined){
			$("#radio_" + data.index +  "_pv_label").html(data.label)
		} else {
			var template = $('#radio_fields_option_Tpl').html();
		    var html = Mustache.to_html(template, data);
		    $("#radio_" + idFather +  "_pv").append(html);
		}
	}

    
  }
</script>

app/views/survey_forms/components/_survey.html.erb
<%= form_for(@survey_form, :url => survey_deliver_path(), :html => {:class => 'form-horizontal'}) do |f| %>
	<% if @survey_form.errors.any? %>
    <div class="alert alert-danger">
      <h2>Problemas ao salvar suas respostas!</h2>
       <% 
        if @survey_form.errors.get(:"answers.survey_field") != nil
          @survey_form.errors.get(:"answers.survey_field").each do |msg| %>
          <ul><%= msg %></ul>
        <% end
      end %>
    </div>
  <% end %>
  <h3><%= @survey_form.title %></h3>
	<hr>
	<p><%= @survey_form.description %></p>
  <%= hidden_field_tag "survey_form[id]", @survey_form.id %>
  <%- @survey_form.survey_fields.each do | survey_field | %>
		<%- if survey_field.survey_type_id == 1 %>
        <div class="form-group">
          <%= label survey_field.title, title(survey_field), :class => "col-lg-4  control-label"%>
          <div class="col-lg-5">
           <%= text_field_tag "survey_form[answers_attributes][][value_answer]", value(survey_field), :id=>"field_#{survey_field.id}_text", :onkeyup=> "$('#value_survey_field_id_#{survey_field.id}').val(this.value)",:class =>  "form-control" %>
           <%= hidden_field_tag "value_survey_field_id[#{survey_field.id}]", "" %>
          </div>
        </div>
		<%- elsif survey_field.survey_type_id == 2 %>
			<div class="form-group">
          <%= label survey_field.title, title(survey_field), :class => "col-lg-4  control-label"%>
          <div class="col-lg-5">
           
           <%= select_tag "survey_form[answers_attributes][][value_answer]",
            options_from_collection_for_select(survey_field.survey_field_options, "value","label"), 
            { :prompt=>"Selecione uma alternativa", :class =>  "form-control", :id=>"field_#{survey_field.id}_cb", :onChange => "$('#' + this.id +'_label').val(this.options[this.selectedIndex].innerHTML)" }%>
        
          </div>
        </div>
    <%- elsif survey_field.survey_type_id == 3 %>
      <div class="form-group">
          <%= label survey_field.title, title(survey_field), :class => "col-lg-4  control-label"%>
          <div class="col-lg-5">
            <% survey_field.survey_field_options.each { |radio| %>
           <div class="radio" id="radio_{{index}}_pv">
            <label>
              <input type="radio" name="radio_<%= radio.survey_field.id %>" value="<%= radio.value %>"  onclick="setValueRadio(this.value, <%= radio.survey_field.id %>)"><label id="radio_<%= radio.survey_field.id %>_label_<%= radio.value %>"><%= radio.label %></label>
            </label>
          </div> 
           <% } %>
           <%= hidden_field_tag "survey_form[answers_attributes][][value_answer]", "", :id=>"field_#{survey_field.id}_cb_value"%>
          
          </div>
        </div>
    <% end %>
    
    <%= hidden_field_tag "survey_form[answers_attributes][][label_answer]", "", :id=>"field_#{survey_field.id}_cb_label"%>
    <%= hidden_field_tag "survey_form[answers_attributes][][survey_field_id]", survey_field.id %>
    <%= hidden_field_tag "survey_form[answers_attributes][][identifier]", @identifier %>

    <% if user_signed_in? %>
      <%= hidden_field_tag "survey_form[answers_attributes][][user_id]", current_user.id %>
     <% end %>
	<% end %>

  <%- if !preview %>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <div class="row">
          <div class="col-md-6"><%= link_to "<button class='btn btn-danger' type='button'>Voltar</button>".html_safe, survey_open_path %></div>
          <div class="col-md-6" style="text-align: right"><%= f.submit :class=>"btn btn-success", :value=>"Salvar"%></div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<SCRIPT TYPE="text/javascript">
  function setValueRadio(value, id){
    $("#field_"+id+"_cb_value").val(value);
    $("#field_"+id+"_cb_label").val($("#radio_"+id+"_label_"+value).html());
  }
</SCRIPT>

app/views/survey_forms/components/_text.html.erb
<script id="textTpl" type="text/template">
  <div id="field{{index}}" class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-2"><h3 class="panel-title"><%= t("app.survey_field.label_name", :field_name =>t("app.survey_field.text.name")) %></h3> <span onclick="removeFieldType('field{{index}}')" style="cursor: pointer"><%=t "app.remove" %></span></div>
        <div class="col-md-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%=t "app.preview" %></h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <label class="col-lg-2 control-label" id="enunciado_{{index}}_pv" for="survey_form_Enunciado">{{title}} {{#mandatory}}*{{/mandatory}}</label>
                <div class="col-lg-9" >
                  <input type="text" class="form-control" id="cb_{{index}}_pv" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-lg-2 control-label" id="mandatory_label" for="survey_form_Enunciado">Obrigatório?</label>
        <div class="col-lg-10" id="radio_{{index}}_pv">
            <div class="radio" id="radio_{{index}}_pv">
                <label><input type="radio" name="mandatory_option_{{index}}" id="mandatory_option_{{index}}" onchange="setMandatory(this)" {{#mandatory}}checked="true"{{/mandatory}} value="true"><label id="radio_{{index}}_pv_label">Sim</label></label><br>
                <label><input type="radio" name="mandatory_option_{{index}}" id="mandatory_option_{{index}}" onchange="setMandatory(this)" {{^mandatory}}checked="true"{{/mandatory}} value="false"><label id="radio_{{index}}_pv_label">Nao</label></label>
            </div>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 control-label"><%=t "app.enunciado" %></label>
        <div class="col-lg-10">
          <input type="text" id="enunciado_{{index}}" name="survey_form[survey_fields_attributes][][title]" class="form-control" placeholder="<%=t "app.enunciado" %>" onFocusOut="changeEnunciado(this)" value="{{title}}"/>
          <input type="hidden" name="survey_form[survey_fields_attributes][][survey_type_id]" value="1" />
          <input type="hidden" name="survey_form[survey_fields_attributes][][order]" value="{{index}}" />
          <input type="hidden" id="mandatory_option_{{index}}_val" name="survey_form[survey_fields_attributes][][mandatory]" value="{{#mandatory}}true{{/mandatory}}{{^mandatory}}false{{/mandatory}}" />
          {{#id}}
            <input type="hidden" name="survey_form[survey_fields_attributes][][id]" value="{{id}}" />
            <input type="hidden" id="field{{index}}_remove" name="survey_form[survey_fields_attributes][][_destroy]" value="0" />
          {{/id}}
        </div>
      </div>
    </div>
  </div>
</script>